"""Repository QA checks in the spirit of Aqua.jl's tests (Python port).

Aqua.jl tests the *quality* of a Julia package's metadata and public API:
dependency integrity, absence of undefined imports, and public-API
consistency. This module brings the same ideas to a Python project:

- every module under the package directory imports cleanly;
- the public API declared in ``__all__`` actually exists on the package;
- no module imports a missing *internal* sibling (dependency completeness
  against ``pyproject.toml`` is deptry's static job).
"""

import importlib
import pkgutil
from pathlib import Path
from typing import cast

import flood_nagoya as pkg

TOP = Path(__file__).resolve().parent.parent
PKG_DIR = TOP / "src/flood_nagoya"

# _version.py is generated by setuptools-scm at build time.
_EXCLUDED = {"flood_nagoya._version"}


def _package_modules() -> list[str]:
    """Dotted names of every importable module under the package directory."""
    return sorted(
        info.name
        for info in pkgutil.walk_packages([str(PKG_DIR)], prefix="flood_nagoya.")
        if info.name not in _EXCLUDED
    )


def test_every_module_imports() -> None:
    """Importing any module in the package must not raise."""
    for name in _package_modules():
        importlib.import_module(name)


def test_public_api_declared_in_all_is_importable() -> None:
    """Names in __all__ resolve to real attributes of the package."""
    # getattr returns Any; cast to a concrete tuple so the QA test itself
    # stays clean under basedpyright (reportAny / reportUnknownVariableType).
    all_names = cast("tuple[str, ...]", getattr(pkg, "__all__", ()))
    for name in all_names:
        assert hasattr(pkg, name), f"{name!r} missing from the package"


def test_no_obviously_undefined_internal_imports() -> None:
    """A package module must not import a sibling module that does not exist.

    Importing every module (test_every_module_imports) already fails on a
    missing *third-party* dependency; this adds a guard for missing
    *internal* modules, which a bad merge can leave dangling. It is shallow
    by design — dependency completeness against pyproject.toml is deptry's
    static job.
    """
    pkg_name = "flood_nagoya"
    for name in _package_modules():
        try:
            importlib.import_module(name)
        except ImportError as exc:
            missing = exc.name or ""
            if missing == pkg_name or missing.startswith(f"{pkg_name}."):
                raise


def test_no_committed_pseudonymisation_salt() -> None:
    """No pseudonymisation salt may be committed (gitleaks is the backstop).

    This offline sweep mirrors the gitleaks ``deidentification-salt`` rule
    so ``just test`` catches a committed salt without needing the hook.
    Only text-like sources are scanned, and the 11 GB ``data/raw`` tree is
    excluded — a full-tree UTF-8 sweep takes minutes and duplicates what
    gitleaks already covers in CI.
    """
    import re

    pattern = re.compile(r"(?i)\b(secret|deidentification|pseudonym)_salt\s*=\s*\S+")
    suffixes = {".py", ".js", ".ts", ".toml", ".yml", ".yaml", ".md", ".sql", ".json", ".html", ".css"}
    offenders = [
        str(p)
        for p in TOP.rglob("*")
        if p.is_file()
        and p.suffix.lower() in suffixes
        and ".git/" not in p.as_posix()
        and ".venv/" not in p.as_posix()
        and "data/raw/" not in p.as_posix()
        and pattern.search(p.read_text(encoding="utf-8", errors="ignore"))
    ]
    assert not offenders, f"pseudonymisation salt committed in: {offenders}"
